name: Configure AI Search

on:
  push:
    branches:
      - main
      - feature/FixIndex11
    paths:
      - "aisearch/**"
      - ".github/workflows/aisearch.workflow.yml"

env:
  ACTIONS_RUNNER_DEBUG: true
  API_BASE_URL: https://srch-piiid-prd.search.windows.net/
  API_VERSION: 2020-06-30-Preview
  API_HEADERS: |
    { 
      "Content-Type": "application/json", 
      "api-key": "${{ secrets.AI_SEARCH_API_KEY }}"
    }

defaults:
  run:
    working-directory: aisearch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy AI Search Datasource
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{env.API_BASE_URL}}datasources?api-version=${{ env.API_VERSION}}'
          method: 'POST'
          customHeaders: ${{env.API_HEADERS}}
          data: |
            { 
              "name": "piiid-datasource", 
              "description": "Demo files to demonstrate Azure AI Search capabilities.", 
              "type": "azureblob", 
              "credentials": { "connectionString": "${{ secrets.SEEDDATA_CONNECTION_STRING }}" }, 
              "container": { "name": "seeddata" } 
            }
        
      - name: Deploy AI Search Skillset
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{env.API_BASE_URL}}skillsets?api-version=${{ env.API_VERSION}}'
          method: 'POST'
          customHeaders: ${{env.API_HEADERS}}
          data: |
            {
              "name": "piiid-skillset",
              "description": "Skillset created from the portal. skillsetName: azureblob-skillset; contentField: merged_content; enrichmentGranularity: document; knowledgeStoreStorageAccount: ;",
              "skills": [
                {
                  "@odata.type": "#Microsoft.Skills.Custom.WebApiSkill",
                  "name": "#1",
                  "description": null,
                  "context": "/document/normalized_images/*",
                  "uri": "https://func-piiid-prd.azurewebsites.net/api/piidocidentifyfunction",
                  "httpMethod": "POST",
                  "timeout": "PT30S",
                  "batchSize": 1,
                  "degreeOfParallelism": 1,
                  "inputs": [
                    {
                      "name": "image",
                      "source": "/document/normalized_images/*"
                    }
                  ],
                  "outputs": [
                    {
                      "name": "firstName",
                      "targetName": "firstName"
                    },
                    {
                      "name": "lastName",
                      "targetName": "lastName"
                    },
                    {
                      "name": "documentType",
                      "targetName": "documentType"
                    }
                  ],
                  "httpHeaders": {}
                }
              ]
            }
