name: Configure AI Search

on:
  push:
    branches:
      - main
      - feature/FixIndex11
    paths:
      - "aisearch/**"
      - ".github/workflows/aisearch.workflow.yml"

env:
  ACTIONS_RUNNER_DEBUG: true
  API_BASE_URL: https://srch-piiid-prd.search.windows.net/
  API_VERSION: 2020-06-30-Preview

defaults:
  run:
    working-directory: aisearch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy AI Search Datasource
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{env.API_BASE_URL}}datasources?api-version=${{ env.API_VERSION}}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "api-key": "${{ secrets.AI_SEARCH_API_KEY }}"}'
          data: |
            { 
              "name": "piiid-datasource", 
              "description": "Demo files to demonstrate Azure AI Search capabilities.", 
              "type": "azureblob", 
              "credentials": { "connectionString": "${{ secrets.SEEDDATA_CONNECTION_STRING }}" }, 
              "container": { "name": "seeddata" } 
            }
